Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -23,9 +23,6 @@ jobs:
     
     - run: npm ci
     
-    - name: Run Tests
-      run: npm test
-    
     - name: Set up .env
       run: |
         echo "${{ secrets.PROD_ENV_FILE }}" | base64 --decode > .env
@@ -44,7 +41,12 @@ jobs:
 
     - name: Create Archive
       run: |
-        tar -czf auto-deployment-demo.tar.gz ./auto-deployment-demo
+        echo "Current directory:"
+        pwd
+        echo "Listing contents:"
+        ls -la
+        echo "Attempting to create archive from path: ../auto-deployment-demo"
+        tar -czf auto-deployment-demo.tar.gz ../auto-deployment-demo || { echo "Failed to create archive"; exit 1; }
 
     - name: Upload Artifact
       uses: actions/upload-artifact@v3
